# Generated by Django 3.2.5 on 2022-01-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
